spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work4
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      #Redis服务器地址
      host: 127.0.0.1
      #端口
      port: 6379
      #使用几号数据库
      database: 0
  servlet:
    multipart:
      # 单个文件的最大限制
      max-file-size: 100MB
      # 单次请求的总大小限制（比如你一次上传多个视频）
      max-request-size: 100MB
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: work.work4.pojo
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: work.work4.pojo
# 阿里云OSS配置
aliyun:
  oss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    access-key-id: "LTAI5tDFsuNpdTXH21DCXLmK"
    access-key-secret: "UbCcqyVi0lZH8dK79j2mGYqFiI95Q8"
    bucket-avatar: work4-avatar # 你的OSS存储空间名称
    bucket-video: work4-video